name: aws-deploy
on: [push]
jobs: 
  deploy-to-aws:
    runs-on: ubuntu-latest
    environment: echo $(echo $GITHUB_REF | cut -d'/' -f 3)
    steps:
      - name: Checkout ${{ github.repository }} repository from branch ${{ github.ref }}
        uses: actions/checkout@v2
      - name: Copy src directory via scp to AWS instances
        uses: horochx/deploy-via-scp@master
        with:
          local: src/*
          remote: /var/www/html/
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
      - name: Build ${{ job.status }}
        run: echo "Build ${{job.status}}!"
